version: '3.8'

services:
  wordpress:
    image: wordpress:6.6.2-php8.1-apache
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html # Mount the wordpress directory
      - ./src:/var/www/html/wp-content/plugins/routepress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_test
    ports:
      - '8080:80'
    networks:
      - wp-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_test
    ports:
      - '3306:3306'
    networks:
      - wp-network

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
