name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          until docker compose exec db mysqladmin ping -h"db" --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Install Composer dependencies inside PHP container
        run: |
          docker compose exec php composer install --prefer-dist --no-interaction

      - name: Install WordPress inside PHP container
        run: |
          docker compose exec php wp core install \
            --url="http://localhost:8080" \
            --title="Test Site" \
            --admin_user="admin" \
            --admin_password="password" \
            --admin_email="admin@example.com" \
            --path="/var/www/html/wordpress"

      - name: Run tests inside PHP container
        run: |
          docker compose exec php vendor/bin/codecept run wpunit -vvv

      - name: Run Psalm inside PHP container
        run: |
          docker compose exec php vendor/bin/psalm

      - name: Shut down Docker Compose
        if: always()
        run: |
          docker compose down
